# Generated by Django 3.1.1 on 2020-09-30 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200930_2315'),
    ]

    operations = [
    ]
